pipeline {

    agent {
        node {
            label 'master'
        }
    }
    environment { 
        PATH = "/root/apictl:$PATH"
    }
    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }

    stages {
        stage('Deploy MobileStore API') {
            steps {
                sh """
                echo "MERGED TO MASTER"
                apictl login pr-test -u admin -p admin -k
                apictl import-api -e pr-test -f MobileStore-v1.0  -k --update -k
                apictl change-status api -a Publish -n MobileStore -v 1.0 -e pr-test -k
                """
            }
        }

        stage('Code Analysis') {
            steps {
                sh """
                echo "Running Code Analysis"
                """
            }
        }

        stage('Build Deploy Code') {
            when {
                branch 'develop'
            }
            steps {
                sh """
                echo "Building Artifact"
                """

                sh """
                echo "Deploying Code"
                """
            }
        }

    }   
}
